site_name: Ecology & Environmental Science Data at Smithsonian
repo_url: https://github.com/Smithsonian/globus-docs
repo_name: Smithsonian/globus-docs

theme:
  name: readthedocs
  navigation_depth: 2

nav:
  - Home: index.md
  - Guide 1: Data Management Basics: guide1-data-management.md
  - Guide 2: File Transfer with Globus: guide2-file-transfer.md
  - Guide 3: HPC & Hydra: guide3-hpc-hydra.md
  - Guide 4: Ecology Workflows: guide4-ecology-workflows.md
  - Guide 5: Data Management Plan (DMP): guide5-data-management-plan.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - pymdownx.superfences